version: "2.2"

networks:
  fincore:
    driver: bridge
services:  
  #mifos-web-server:
  #  image: com.mx.fintecheando.nginx.mifosx.18.03.01
  #  restart: always
  #  ports:
  #    - 443:8443
  #    - 80:8080    
  #  networks:
  #    - fincore
  #  depends_on:
  #    mifos-app-server:
  #      condition: service_healthy
  mifos-app-server:
    image: com.mx.fintecheando.tomcat.mifosx.18.03.01
    restart: always
    ports:
      - 8443:8443
      - 8080:8080
    networks:
      - fincore
    depends_on:
      mifos-db-server:
        condition: service_healthy
      mifos-sms-server:
        condition: service_healthy
    healthcheck:
      test: curl -kfsS https://127.0.0.1:8443 | grep 'Tomcat' | wc -l 
      interval: 5s
      retries: 20        
  mifos-db-server:
    image: com.mx.fintecheando.mysql.mifosx.18.03.01
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test:  mysqladmin --user=root --password=mysql ping -h localhost
      interval: 5s
      retries: 20
    networks:
      - fincore  
  mifos-sms-server:
    image: com.mx.fintecheando.activemq.mifosx.18.03.01
    restart: always
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
    healthcheck:
      test:  curl -u admin:admin -s http://localhost:8161/admin
      interval: 5s
      retries: 20  
    networks:
      - fincore
# ###########################
# # Setup the PHPMyAdmin container
# ###########################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mifos-db-server
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    depends_on:
      - mifos-db-server
    networks:
      - fincore        
